# Generated by Django 5.2.5 on 2026-01-11 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_entidad', models.CharField(choices=[('Proveedor', 'Proveedor'), ('Cliente', 'Cliente'), ('Ambos', 'Ambos')], max_length=20)),
                ('tipo_documento', models.CharField(choices=[('RUC', 'RUC'), ('DNI', 'DNI')], max_length=10)),
                ('numero_documento', models.CharField(max_length=20)),
                ('nombre_razon_social', models.CharField(max_length=200)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('Factura', 'Factura'), ('Boleta', 'Boleta')], max_length=20)),
                ('operacion', models.CharField(choices=[('Compra', 'Compra'), ('Venta', 'Venta')], max_length=20)),
                ('serie', models.CharField(max_length=10)),
                ('numero', models.CharField(max_length=20)),
                ('fecha_emision', models.DateField()),
                ('moneda', models.CharField(default='PEN', max_length=3)),
                ('tipo_cambio', models.DecimalField(decimal_places=3, default=1.0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('igv', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('es_flete', models.BooleanField(default=False)),
                ('comprobante_asociado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.comprobante')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.entidad')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50)),
                ('nombre_interno', models.CharField(max_length=200)),
                ('nombres_alternativos', models.JSONField(blank=True, default=list)),
                ('stock_actual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio_compra_referencial', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.categoriaproducto')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='ComprobanteDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal_linea', models.DecimalField(decimal_places=2, max_digits=12)),
                ('comprobante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.comprobante')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.producto')),
            ],
        ),
    ]
