# Generated by Django 5.2.5 on 2026-01-11 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_categoriagasto_gastooperativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prestamista', models.CharField(max_length=200)),
                ('moneda', models.CharField(default='PEN', max_length=3)),
                ('monto_capital', models.DecimalField(decimal_places=2, max_digits=12)),
                ('porcentaje_interes', models.DecimalField(decimal_places=2, max_digits=5)),
                ('monto_interes', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagado', 'Pagado')], default='Pendiente', max_length=20)),
                ('fecha_prestamo', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('comprobante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestamos', to='core.comprobante')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
        ),
    ]
