# Generated by Django 5.2.5 on 2026-01-11 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_prestamo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCambioDia',
            fields=[
                ('fecha', models.DateField(primary_key=True, serialize=False)),
                ('compra', models.DecimalField(decimal_places=3, max_digits=6)),
                ('venta', models.DecimalField(decimal_places=3, max_digits=6)),
                ('fuente', models.CharField(default='SUNAT / SBS', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CuentaEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Parcial', 'Parcial'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=20)),
                ('fecha_vencimiento', models.DateField()),
                ('comprobante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_estado', to='core.comprobante')),
            ],
        ),
    ]
