# Generated by Django 5.2.5 on 2026-01-11 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_comprobante_estado_sunat_movimientofinanciero'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientofinanciero',
            name='moneda',
            field=models.CharField(default='PEN', max_length=3),
        ),
    ]
