# Generated by Django 5.2.5 on 2026-01-13 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_movimientofinanciero_options_caja_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobantedetalle',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.producto'),
        ),
    ]
