# Generated by Django 5.2.5 on 2026-01-14 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_comprobantedetalle_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificadoRetencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie_numero', models.CharField(max_length=20)),
                ('fecha_emision', models.DateField()),
                ('monto_total_pen', models.DecimalField(decimal_places=2, max_digits=12)),
                ('agente_retencion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.entidad')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
            options={
                'verbose_name': 'Certificado de Retención',
                'verbose_name_plural': 'Certificados de Retención',
            },
        ),
        migrations.CreateModel(
            name='RetencionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_retencion_pen', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_descuento_moneda_origen', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo_cambio_aplicado', models.DecimalField(decimal_places=4, max_digits=10)),
                ('certificado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.certificadoretencion')),
                ('comprobante', models.ForeignKey(limit_choices_to={'operacion': 'Venta'}, on_delete=django.db.models.deletion.CASCADE, to='core.comprobante')),
            ],
        ),
    ]
