# Generated by Django 5.2.5 on 2026-01-14 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_certificadoretencion_retenciondetalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientofinanciero',
            name='diferencia_cambio_soles',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='movimientofinanciero',
            name='tipo_cambio_operacion',
            field=models.DecimalField(decimal_places=3, default=1.0, max_digits=10),
        ),
    ]
