# Generated by Django 5.2.5 on 2026-01-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_movimientofinanciero_diferencia_cambio_soles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobante',
            name='tipo_documento',
            field=models.CharField(choices=[('Factura', 'Factura'), ('Boleta', 'Boleta'), ('Recibo', 'Recibo / Nota de Venta'), ('Otros', 'Otros (AliExpress/Amazon)')], max_length=20),
        ),
    ]
