# Generated by Django 5.2.5 on 2026-01-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_comprobante_tipo_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobante',
            name='es_escudo_tributario',
            field=models.BooleanField(default=False),
        ),
    ]
