# Generated by Django 5.2.5 on 2026-01-16 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_comprobante_es_escudo_tributario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuota',
            options={'ordering': ['fecha_vencimiento'], 'verbose_name': 'Cuota de Pago/Cobro', 'verbose_name_plural': 'Cuotas de Pago/Cobro'},
        ),
        migrations.AddField(
            model_name='cuota',
            name='prestamo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='core.prestamo'),
        ),
        migrations.AlterField(
            model_name='cuota',
            name='cuenta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='core.cuentaestado'),
        ),
    ]
