# Generated by Django 5.2.5 on 2026-01-20 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_cuota_options_cuota_prestamo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeclaracionMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=7)),
                ('tributo', models.CharField(choices=[('1011', 'IGV'), ('3111', 'Renta')], max_length=4)),
                ('monto_declarado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('numero_orden', models.CharField(max_length=20)),
                ('fecha_presentacion', models.DateField()),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
            options={
                'verbose_name': 'Declaración PDT 0621',
                'verbose_name_plural': 'Declaraciones PDT 0621',
            },
        ),
        migrations.CreateModel(
            name='PagoImpuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_pago', models.DateField()),
                ('numero_operacion', models.CharField(max_length=20)),
                ('declaracion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='core.declaracionmensual')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('movimiento', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.movimientofinanciero')),
            ],
            options={
                'verbose_name': 'Pago SUNAT 1662',
                'verbose_name_plural': 'Pagos SUNAT 1662',
            },
        ),
    ]
