# Generated by Django 5.2.5 on 2026-01-20 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_declaracionmensual_pagoimpuesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientofinanciero',
            name='itf_monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
