# Generated by Django 5.2.5 on 2026-01-20 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_movimientofinanciero_itf_monto'),
    ]

    operations = [
        migrations.CreateModel(
            name='CierreMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=7)),
                ('igv_final_calculado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldo_a_favor_generado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cerrado', models.BooleanField(default=False)),
                ('fecha_cierre', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
            options={
                'verbose_name': 'Cierre Mensual Tributario',
                'verbose_name_plural': 'Cierres Mensuales Tributarios',
                'unique_together': {('empresa', 'periodo')},
            },
        ),
    ]
