# Generated by Django 5.2.5 on 2026-01-20 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_cierremensual'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagoimpuesto',
            name='periodo',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='pagoimpuesto',
            name='tributo_codigo',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
