# Generated by Django 5.2.5 on 2026-02-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_pagoimpuesto_periodo_pagoimpuesto_tributo_codigo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rol',
            options={'verbose_name': 'Rol', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterField(
            model_name='rol',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='rol',
            name='permisos',
            field=models.JSONField(default=dict, help_text='Define qué puede ver en el Dashboard'),
        ),
    ]
