# Generated by Django 5.2.5 on 2026-02-05 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_empresa_correo_empresa_direccion_empresa_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta_bancaria',
            name='cci',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código de Cuenta Interbancaria (CCI)'),
        ),
    ]
