# Generated by Django 5.2.5 on 2026-02-07 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_cuenta_bancaria_cci'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logauditoria',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.empresa'),
        ),
    ]
