# Generated by Django 5.2.5 on 2026-02-07 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_logauditoria_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobantedetalle',
            name='descripcion_libre',
            field=models.TextField(blank=True, null=True),
        ),
    ]
