# Generated by Django 5.2.5 on 2026-02-09 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_comprobantedetalle_descripcion_libre'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_venta_referencial',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_compra_referencial',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
