# Generated by Django 5.2.5 on 2026-02-12 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_producto_precio_venta_referencial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AjusteStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Ingreso', 'Ingreso (Suma)'), ('Egreso', 'Egreso (Resta)')], max_length=10)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motivo', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ajustes', to='core.producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ajuste de Stock',
                'verbose_name_plural': 'Ajustes de Stock',
            },
        ),
    ]
