# Generated by Django 5.2.5 on 2026-02-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_ajustestock'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuota',
            name='saldo_cuota',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
